version: '3.8'  # Menentukan versi Docker Compose

services:
  openssh-server:
    image: vm-siluman
    container_name: local-node1
    hostname: dagimal01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PUBLIC_KEY=yourpublickey #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=dagimal102938 #optional
      - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=dagimal #optional
      - LOG_STDOUT= #optional
    volumes:
      - ./data:/etc
      - ./data:/opt
    ports:
      - 2221:22
    restart: unless-stopped
    networks:
      local-vm:  # Menggunakan jaringan yang didefinisikan di bawah
        ipv4_address: 192.168.100.2  # Ganti dengan alamat IP yang sesuai

networks:
  local-vm:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Pastikan subnet tidak bertabrakan
